/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface TheDataWalletContract
  extends Truffle.Contract<TheDataWalletInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<TheDataWalletInstance>;
}

export interface Delta {
  name: "Delta";
  args: {
    _from: string;
    _to: string;
    _deltaJson: string;
    0: string;
    1: string;
    2: string;
  };
}

export interface DeltaRequest {
  name: "DeltaRequest";
  args: {
    _from: string;
    _to: string;
    _value: BN;
    _requestID: BN;
    _modelJson: string;
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: string;
  };
}

type AllEvents = Delta | DeltaRequest;

export interface TheDataWalletInstance extends Truffle.ContractInstance {
  requestDelta: {
    (
      receiver: string,
      amount: number | BN | string,
      modelJson: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      receiver: string,
      amount: number | BN | string,
      modelJson: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
    sendTransaction(
      receiver: string,
      amount: number | BN | string,
      modelJson: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      receiver: string,
      amount: number | BN | string,
      modelJson: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  publishDelta: {
    (
      receiver: string,
      deltaJson: string,
      requestID: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      receiver: string,
      deltaJson: string,
      requestID: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
    sendTransaction(
      receiver: string,
      deltaJson: string,
      requestID: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      receiver: string,
      deltaJson: string,
      requestID: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  getBalance(addr: string, txDetails?: Truffle.TransactionDetails): Promise<BN>;

  transfer: {
    (
      addr: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      addr: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
    sendTransaction(
      addr: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      addr: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    requestDelta: {
      (
        receiver: string,
        amount: number | BN | string,
        modelJson: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        receiver: string,
        amount: number | BN | string,
        modelJson: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<BN>;
      sendTransaction(
        receiver: string,
        amount: number | BN | string,
        modelJson: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        receiver: string,
        amount: number | BN | string,
        modelJson: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    publishDelta: {
      (
        receiver: string,
        deltaJson: string,
        requestID: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        receiver: string,
        deltaJson: string,
        requestID: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<boolean>;
      sendTransaction(
        receiver: string,
        deltaJson: string,
        requestID: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        receiver: string,
        deltaJson: string,
        requestID: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    getBalance(
      addr: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    transfer: {
      (
        addr: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        addr: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<boolean>;
      sendTransaction(
        addr: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        addr: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
